export const getHeroImage = id => {
  // id = id.toLowerCase().replace(/ /g, "_");

  // let name = "";
  // switch (id) {
  //   case 1:
  //     name = "antimage";
  //     break;
  //   case 2:
  //     name = "axe";
  //     break;
  //   case 3:
  //     name = "bane";
  //     break;
  //     case 4:
  //     name = ""
  // }

  if (id === 1) id = "antimage";
  if (id === 2) id = "axe";
  if (id === 3) id = "bane";
  if (id === 4) id = "bloodseeker";
  if (id === 5) id = "crystal_maiden";
  if (id === 6) id = "drow_ranger";
  if (id === 7) id = "earthshaker";
  if (id === 8) id = "juggernaut";
  if (id === 9) id = "mirana";
  if (id === 10) id = "morphling";
  if (id === 11) id = "nevermore";
  if (id === 12) id = "phantom_lancer";
  if (id === 13) id = "puck";
  if (id === 14) id = "pudge";
  if (id === 15) id = "razor";
  if (id === 16) id = "sand_king";

  if (id === 17) id = "storm_spirit";
  if (id === 18) id = "sven";
  if (id === 19) id = "tiny";
  if (id === 20) id = "vengefulspirit";
  if (id === 21) id = "windrunner";
  if (id === 22) id = "zuus";
  if (id === 23) id = "kunkka";
  if (id === 25) id = "lina";
  if (id === 26) id = "lion";
  if (id === 27) id = "shadow_shaman";
  if (id === 28) id = "slardar";
  if (id === 29) id = "tidehunter";
  if (id === 30) id = "witch_doctor";
  if (id === 31) id = "lich";
  if (id === 32) id = "riki";
  if (id === 33) id = "enigma";
  if (id === 34) id = "tinker";
  if (id === 35) id = "sniper";
  if (id === 36) id = "necrolyte";
  if (id === 37) id = "warlock";
  if (id === 38) id = "beastmaster";
  if (id === 39) id = "queenofpain";
  if (id === 40) id = "venomancer";
  if (id === 41) id = "faceless_void";
  if (id === 42) id = "skeleton_king";
  if (id === 43) id = "death_prophet";
  if (id === 44) id = "phantom_assassin";
  if (id === 45) id = "pugna";
  if (id === 46) id = "templar_assassin";
  if (id === 47) id = "viper";
  if (id === 48) id = "luna";
  if (id === 49) id = "dragon_knight";
  if (id === 50) id = "dazzle";
  if (id === 51) id = "rattletrap";
  if (id === 52) id = "leshrac";
  if (id === 53) id = "furion";
  if (id === 54) id = "life_stealer";
  if (id === 55) id = "dark_seer";
  if (id === 56) id = "clinkz";
  if (id === 57) id = "omniknight";
  if (id === 58) id = "enchantress";
  if (id === 59) id = "huskar";
  if (id === 60) id = "night_stalker";
  if (id === 61) id = "broodmother";
  if (id === 62) id = "bounty_hunter";
  if (id === 63) id = "weaver";
  if (id === 64) id = "jakiro";
  if (id === 65) id = "batrider";
  if (id === 66) id = "chen";
  if (id === 67) id = "spectre";
  if (id === 68) id = "ancient_apparition";
  if (id === 69) id = "doom_bringer";
  if (id === 70) id = "ursa";
  if (id === 71) id = "spirit_breaker";
  if (id === 72) id = "gyrocopter";
  if (id === 73) id = "alchemist";
  if (id === 74) id = "invoker";
  if (id === 75) id = "silencer";
  if (id === 76) id = "obsidian_destroyer";
  if (id === 77) id = "lycan";
  if (id === 78) id = "brewmaster";
  if (id === 79) id = "shadow_demon";
  if (id === 80) id = "lone_druid";
  if (id === 81) id = "chaos_knight";
  if (id === 82) id = "meepo";
  if (id === 83) id = "treant";
  if (id === 84) id = "ogre_magi";
  if (id === 85) id = "undying";
  if (id === 86) id = "rubick";
  if (id === 87) id = "disruptor";
  if (id === 88) id = "nyx_assassin";
  if (id === 89) id = "naga_siren";
  if (id === 90) id = "keeper_of_the_light";
  if (id === 91) id = "wisp";
  if (id === 92) id = "visage";
  if (id === 93) id = "slark";
  if (id === 94) id = "medusa";
  if (id === 95) id = "troll_warlord";
  if (id === 96) id = "centaur";
  if (id === 97) id = "magnataur";
  if (id === 98) id = "shredder";
  if (id === 99) id = "bristleback";
  if (id === 100) id = "tusk";
  if (id === 101) id = "skywrath_mage";
  if (id === 102) id = "abaddon";
  if (id === 103) id = "elder_titan";
  if (id === 104) id = "legion_commander";
  if (id === 105) id = "techies";
  if (id === 106) id = "ember_spirit";
  if (id === 107) id = "earth_spirit";
  if (id === 108) id = "abyssal_underlord";
  if (id === 109) id = "terrorblade";
  if (id === 110) id = "phoenix";
  if (id === 111) id = "oracle";
  if (id === 112) id = "winter_wyvern";
  if (id === 113) id = "arc_warden";
  if (id === 114) id = "monkey_king";
  if (id === 119) id = "dark_willow";
  if (id === 120) id = "pangolier";

  return `https://api.opendota.com/apps/dota2/images/heroes/${id}_sb.png`;
};
