export const GET_TEAMS = "GET_TEAMS";
export const GET_TEAM_MATCHES = "GET_TEAM_MATCHES";
export const GET_TEAM_PLAYERS = "GET_TEAM_PLAYERS";
export const GET_TEAM_HEROES = "GET_TEAM_HEROES";

export const GET_MATCHES = "GET_MATCHES";
